package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"log"
	"net/http"
	"time"

	"github.com/khoirulhasin/globe_tracker_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/globe_tracker_api/app/models"
	"github.com/khoirulhasin/globe_tracker_api/helpers"
)

// CreateAnswer is the resolver for the CreateAnswer field.
func (r *mutationResolver) CreateAnswer(ctx context.Context, questionID string, optionID string) (*models.Response, error) {
	ans := &models.Answer{
		QuestionID: questionID,
		OptionID:   optionID,
	}

	if ok, errorString := helpers.ValidateInputs(*ans); !ok {
		return &models.Response{
			Message: errorString,
			Status:  http.StatusUnprocessableEntity,
		}, nil
	}

	//check if the answer is correct:
	correctOpt, err := r.QuestionOptionRepository.GetQuestionOptionByID(optionID)
	if err != nil {
		return error_handlers.PanicException(error_handlers.InternalError)
	}

	if correctOpt.IsCorrect == true {
		ans.IsCorrect = true
	} else {
		ans.IsCorrect = false
	}

	ans.CreatedAt = time.Now()
	ans.UpdatedAt = time.Now()

	answer, err := r.AnsRepository.CreateAnswer(ans)
	if err != nil {
		log.Println("Answer creation error: ", err)
		return error_handlers.PanicException(error_handlers.InternalError)
	}

	return helpers.ResponseDataFormat(answer, "Answer")
}

// UpdateAnswer is the resolver for the UpdateAnswer field.
func (r *mutationResolver) UpdateAnswer(ctx context.Context, id string, questionID string, optionID string) (*models.Response, error) {
	gc, _ := helpers.GinContextFromContext(ctx)
	error_handlers.PanicHandler(gc)

	ans, err := r.AnsRepository.GetAnswerByID(id)
	if err != nil {
		log.Println("Error getting the answer to update: ", err)
		return &models.Response{
			Message: "Error getting the answer",
			Status:  http.StatusUnprocessableEntity,
		}, nil
	}

	ans.OptionID = optionID
	ans.QuestionID = questionID
	ans.UpdatedAt = time.Now()

	if ok, errorString := helpers.ValidateInputs(*ans); !ok {
		return &models.Response{
			Message: errorString,
			Status:  http.StatusUnprocessableEntity,
		}, nil
	}

	//check if the answer is correct:
	correctOpt, err := r.AnsRepository.GetAnswerByID(optionID)
	if err != nil {
		return error_handlers.PanicException(error_handlers.InternalError)
	}

	if correctOpt.IsCorrect == true {
		ans.IsCorrect = true
	} else {
		ans.IsCorrect = false
	}

	answer, err := r.AnsRepository.UpdateAnswer(ans)
	if err != nil {
		log.Println("Answer updating error: ", err)
		return error_handlers.PanicException(error_handlers.InternalError)
	}

	return helpers.ResponseDataFormat(answer, "Answer")
}

// DeleteAnswer is the resolver for the DeleteAnswer field.
func (r *mutationResolver) DeleteAnswer(ctx context.Context, id string) (*models.Response, error) {
	gc, _ := helpers.GinContextFromContext(ctx)
	error_handlers.PanicHandler(gc)
	err := r.AnsRepository.DeleteAnswer(id)
	if err != nil {
		return error_handlers.PanicException(error_handlers.InternalError)
	}

	return helpers.SuccessResponseFormat()
}

// GetOneAnswer is the resolver for the GetOneAnswer field.
func (r *queryResolver) GetOneAnswer(ctx context.Context, id string) (*models.Response, error) {
	gc, _ := helpers.GinContextFromContext(ctx)
	error_handlers.PanicHandler(gc)
	answer, err := r.AnsRepository.GetAnswerByID(id)
	if err != nil {
		log.Println("getting answer error: ", err)
		return error_handlers.PanicException(error_handlers.InternalError)
	}

	return helpers.ResponseDataFormat(answer, "Answer")
}

// GetAllQuestionAnswers is the resolver for the GetAllQuestionAnswers field.
func (r *queryResolver) GetAllQuestionAnswers(ctx context.Context, questionID string) (*models.ListResponse, error) {
	gc, _ := helpers.GinContextFromContext(ctx)
	error_handlers.PanicHandler(gc)
	answers, err := r.AnsRepository.GetAllQuestionAnswers(questionID)
	if err != nil {
		log.Println("getting all questions error: ", err)
		return error_handlers.ListPanicException(error_handlers.InternalError)
	}

	var data []models.Data
	for _, ans := range answers {
		data = append(data, models.Data(*ans))
	}

	return helpers.ListResponseDataFormat(data, "Answers")
}
