package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/generated"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateCam is the resolver for the CreateCam field.
func (r *mutationResolver) CreateCam(ctx context.Context, createCamInput models.CreateCamInput) (any, error) {
	cam := &models.Cam{
		Name:      createCamInput.Name,
		Code:      createCamInput.Code,
		Source:    createCamInput.Source,
		RunOnInit: createCamInput.RunOnInit,
	}
	response, err := r.CamRepository.CreateCam(ctx, cam)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateCam is the resolver for the UpdateCam field.
func (r *mutationResolver) UpdateCam(ctx context.Context, id int, updateCamInput models.UpdateCamInput) (any, error) {
	cam := &models.Cam{
		Name:      updateCamInput.Name,
		Code:      updateCamInput.Code,
		Source:    updateCamInput.Source,
		RunOnInit: updateCamInput.RunOnInit,
	}

	response, err := r.CamRepository.UpdateCam(ctx, int32(id), cam)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateCamByUUID is the resolver for the UpdateCamByUuid field.
func (r *mutationResolver) UpdateCamByUUID(ctx context.Context, uuid uuid.UUID, updateCamInput models.UpdateCamInput) (any, error) {
	cam := &models.Cam{
		Name:      updateCamInput.Name,
		Code:      updateCamInput.Code,
		Source:    updateCamInput.Source,
		RunOnInit: updateCamInput.RunOnInit,
	}

	response, err := r.CamRepository.UpdateCamByUUID(ctx, uuid.String(), cam)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteCam is the resolver for the DeleteCam field.
func (r *mutationResolver) DeleteCam(ctx context.Context, id int) (any, error) {
	panic(fmt.Errorf("not implemented: DeleteCam - DeleteCam"))
}

// DeleteCamByUUID is the resolver for the DeleteCamByUuid field.
func (r *mutationResolver) DeleteCamByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.CamRepository.DeleteCamByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneCam is the resolver for the GetOneCam field.
func (r *queryResolver) GetOneCam(ctx context.Context, id int) (any, error) {
	cam, err := r.CamRepository.GetCamByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return cam, nil
}

// GetOneCamByUUID is the resolver for the GetOneCamByUuid field.
func (r *queryResolver) GetOneCamByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	cam, err := r.CamRepository.GetCamByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return cam, nil
}

// GetCamByStateID is the resolver for the GetCamByStateId field.
func (r *queryResolver) GetCamByStateID(ctx context.Context, stateID int) ([]any, error) {
	cams, err := r.CamRepository.GetCamByStateID(ctx, int32(stateID))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(cams))
	for i, cam := range cams {
		response[i] = cam
	}

	return response, nil
}

// GetAllCams is the resolver for the GetAllCams field.
func (r *queryResolver) GetAllCams(ctx context.Context) ([]any, error) {
	cams, err := r.CamRepository.GetAllCams(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(cams))
	for i, cam := range cams {
		response[i] = cam
	}

	return response, nil
}

// PageCam is the resolver for the PageCam field.
func (r *queryResolver) PageCam(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.CamRepository.PageCam(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
