package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateDevice is the resolver for the CreateDevice field.
func (r *mutationResolver) CreateDevice(ctx context.Context, createDeviceInput models.CreateDeviceInput) (any, error) {
	device := &models.Device{
		Imei:    createDeviceInput.Imei,
		Name:    createDeviceInput.Name,
		OwnerID: createDeviceInput.OwnerID,
		ShipID:  createDeviceInput.ShipID,
	}
	response, err := r.DeviceRepository.CreateDevice(ctx, device)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateDevice is the resolver for the UpdateDevice field.
func (r *mutationResolver) UpdateDevice(ctx context.Context, id int, updateDeviceInput models.UpdateDeviceInput) (any, error) {
	device := &models.Device{
		Imei:    updateDeviceInput.Imei,
		Name:    updateDeviceInput.Name,
		OwnerID: updateDeviceInput.OwnerID,
		ShipID:  updateDeviceInput.ShipID,
	}

	response, err := r.DeviceRepository.UpdateDevice(ctx, int32(id), device)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateDeviceByUUID is the resolver for the UpdateDeviceByUuid field.
func (r *mutationResolver) UpdateDeviceByUUID(ctx context.Context, uuid uuid.UUID, updateDeviceInput *models.UpdateDeviceInput) (any, error) {
	device := &models.Device{
		Imei:    updateDeviceInput.Imei,
		Name:    updateDeviceInput.Name,
		OwnerID: updateDeviceInput.OwnerID,
		ShipID:  updateDeviceInput.ShipID,
	}

	response, err := r.DeviceRepository.UpdateDeviceByUUID(ctx, uuid.String(), device)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteDevice is the resolver for the DeleteDevice field.
func (r *mutationResolver) DeleteDevice(ctx context.Context, id int) (any, error) {
	err := r.DeviceRepository.DeleteDevice(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteDeviceByUUID is the resolver for the DeleteDeviceByUuid field.
func (r *mutationResolver) DeleteDeviceByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.DeviceRepository.DeleteDeviceByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneDevice is the resolver for the GetOneDevice field.
func (r *queryResolver) GetOneDevice(ctx context.Context, id int) (any, error) {
	device, err := r.DeviceRepository.GetDeviceByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return device, nil
}

// GetOneDeviceByUUID is the resolver for the GetOneDeviceByUuid field.
func (r *queryResolver) GetOneDeviceByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	device, err := r.DeviceRepository.GetDeviceByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return device, nil
}

// GetAllDevices is the resolver for the GetAllDevices field.
func (r *queryResolver) GetAllDevices(ctx context.Context) ([]any, error) {
	devices, err := r.DeviceRepository.GetAllDevices(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(devices))
	for i, device := range devices {
		response[i] = device
	}

	return response, nil
}

// PageDevice is the resolver for the PageDevice field.
func (r *queryResolver) PageDevice(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.DeviceRepository.PageDevice(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
