package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateDriver is the resolver for the CreateDriver field.
func (r *mutationResolver) CreateDriver(ctx context.Context, createDriverInput models.CreateDriverInput) (any, error) {
	driver := &models.Driver{
		Name:             createDriverInput.Name,
		NumberIdentifier: createDriverInput.NumberIdentifier,
		Address:          createDriverInput.Address,
	}
	response, err := r.DriverRepository.CreateDriver(ctx, driver)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateDriver is the resolver for the UpdateDriver field.
func (r *mutationResolver) UpdateDriver(ctx context.Context, id int, updateDriverInput models.UpdateDriverInput) (any, error) {
	driver := &models.Driver{
		Name:             updateDriverInput.Name,
		NumberIdentifier: updateDriverInput.NumberIdentifier,

		Address: updateDriverInput.Address,
	}

	response, err := r.DriverRepository.UpdateDriver(ctx, int32(id), driver)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateDriverByUUID is the resolver for the UpdateDriverByUuid field.
func (r *mutationResolver) UpdateDriverByUUID(ctx context.Context, uuid uuid.UUID, updateDriverInput models.UpdateDriverInput) (any, error) {
	driver := &models.Driver{
		Name:             updateDriverInput.Name,
		NumberIdentifier: updateDriverInput.NumberIdentifier,
		Address:          updateDriverInput.Address,
	}

	response, err := r.DriverRepository.UpdateDriverByUUID(ctx, uuid.String(), driver)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteDriver is the resolver for the DeleteDriver field.
func (r *mutationResolver) DeleteDriver(ctx context.Context, id int) (any, error) {
	err := r.DriverRepository.DeleteDriver(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteDriverByUUID is the resolver for the DeleteDriverByUuid field.
func (r *mutationResolver) DeleteDriverByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.DriverRepository.DeleteDriverByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneDriver is the resolver for the GetOneDriver field.
func (r *queryResolver) GetOneDriver(ctx context.Context, id int) (any, error) {
	driver, err := r.DriverRepository.GetDriverByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return driver, nil
}

// GetOneDriverByUUID is the resolver for the GetOneDriverByUuid field.
func (r *queryResolver) GetOneDriverByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	driver, err := r.DriverRepository.GetDriverByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return driver, nil
}

// GetAllDrivers is the resolver for the GetAllDrivers field.
func (r *queryResolver) GetAllDrivers(ctx context.Context) ([]any, error) {
	drivers, err := r.DriverRepository.GetAllDrivers(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(drivers))
	for i, driver := range drivers {
		response[i] = driver
	}

	return response, nil
}

// PageDriver is the resolver for the PageDriver field.
func (r *queryResolver) PageDriver(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.DriverRepository.PageDriver(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
