package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/helpers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateGeofence is the resolver for the CreateGeofence field.
func (r *mutationResolver) CreateGeofence(ctx context.Context, createGeofenceInput models.CreateGeofenceInput) (any, error) {
	token, err := helpers.GetToken(ctx)

	if err != nil {
		return nil, err
	}

	userID, err := helpers.GetUserID(token.(string))

	if err != nil {
		return nil, err
	}
	return r.GeofenceRepository.CreateGeofence(ctx, &createGeofenceInput, userID)
}

// UpdateGeofence is the resolver for the UpdateGeofence field.
func (r *mutationResolver) UpdateGeofence(ctx context.Context, id int, updateGeofenceInput models.UpdateGeofenceInput) (any, error) {
	return r.GeofenceRepository.UpdateGeofence(ctx, int32(id), &updateGeofenceInput)
}

// UpdateGeofenceByUUID is the resolver for the UpdateGeofenceByUuid field.
func (r *mutationResolver) UpdateGeofenceByUUID(ctx context.Context, uuid uuid.UUID, updateGeofenceInput models.UpdateGeofenceInput) (any, error) {
	return r.GeofenceRepository.UpdateGeofenceByUUID(ctx, uuid.String(), &updateGeofenceInput)
}

// DeleteGeofence is the resolver for the DeleteGeofence field.
func (r *mutationResolver) DeleteGeofence(ctx context.Context, id int) (any, error) {
	err := r.GeofenceRepository.DeleteGeofence(ctx, int32(id))
	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}
	return nil, nil
}

// DeleteGeofenceByUUID is the resolver for the DeleteGeofenceByUuid field.
func (r *mutationResolver) DeleteGeofenceByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.GeofenceRepository.DeleteGeofenceByUUID(ctx, uuid.String())
	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}
	return nil, nil
}

// GetAllGeofences is the resolver for the GetAllGeofences field.
func (r *queryResolver) GetAllGeofences(ctx context.Context) (any, error) {
	return r.GeofenceRepository.GetAllGeofences(ctx)
}

// GetOneGeofence is the resolver for the GetOneGeofence field.
func (r *queryResolver) GetOneGeofence(ctx context.Context, id int) (any, error) {
	return r.GeofenceRepository.GetGeofenceByID(ctx, int32(id))
}

// GetOneGeofenceByUUID is the resolver for the GetOneGeofenceByUuid field.
func (r *queryResolver) GetOneGeofenceByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	return r.GeofenceRepository.GetGeofenceByUUID(ctx, uuid.String())
}

// PageGeofence is the resolver for the PageGeofence field.
func (r *queryResolver) PageGeofence(ctx context.Context, pageInput *models.PageInput) (any, error) {
	limit, offset, sortField, sortOrder, search, filters := pkg.PageInputIsNil(pageInput)

	// pagination := models.Pagination{
	// 	Limit: limit, Offset: offset,
	// 	SortField: sortField, SortOrder: sortOrder,
	// 	Search: search, Filters: filters,
	// }

	var mappedFilters []*models.Filter
	for _, f := range filters {
		mappedFilters = append(mappedFilters, &models.Filter{
			Key:      f.Key,
			Operator: f.Operator,
			Value:    f.Value,
		})
	}

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
		Filters:   mappedFilters,
	}

	return r.GeofenceRepository.PageGeofence(ctx, pagination)
}
