package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateMarker is the resolver for the CreateMarker field.
func (r *mutationResolver) CreateMarker(ctx context.Context, createMarkerInput models.CreateMarkerInput) (any, error) {
	marker := &models.Marker{
		Title:        createMarkerInput.Title,
		Lat:          createMarkerInput.Lat,
		Lng:          createMarkerInput.Lng,
		Start:        createMarkerInput.Duration.Start,
		End:          createMarkerInput.Duration.End,
		MarkerTypeID: createMarkerInput.MarkerTypeID,
		Description:  createMarkerInput.Description,
	}
	response, err := r.MarkerRepository.CreateMarker(ctx, marker)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateMarker is the resolver for the UpdateMarker field.
func (r *mutationResolver) UpdateMarker(ctx context.Context, id int, updateMarkerInput models.UpdateMarkerInput) (any, error) {
	marker := &models.Marker{
		Title:        updateMarkerInput.Title,
		Lat:          updateMarkerInput.Lat,
		Lng:          updateMarkerInput.Lng,
		Start:        updateMarkerInput.Duration.Start,
		End:          updateMarkerInput.Duration.End,
		MarkerTypeID: updateMarkerInput.MarkerTypeID,
		Description:  updateMarkerInput.Description,
	}

	response, err := r.MarkerRepository.UpdateMarker(ctx, int32(id), marker)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateMarkerByUUID is the resolver for the UpdateMarkerByUuid field.
func (r *mutationResolver) UpdateMarkerByUUID(ctx context.Context, uuid uuid.UUID, updateMarkerInput *models.UpdateMarkerInput) (any, error) {
	marker := &models.Marker{
		Title:        updateMarkerInput.Title,
		Lat:          updateMarkerInput.Lat,
		Lng:          updateMarkerInput.Lng,
		Start:        updateMarkerInput.Duration.Start,
		End:          updateMarkerInput.Duration.End,
		MarkerTypeID: updateMarkerInput.MarkerTypeID,
		Description:  updateMarkerInput.Description,
	}

	response, err := r.MarkerRepository.UpdateMarkerByUUID(ctx, uuid.String(), marker)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteMarker is the resolver for the DeleteMarker field.
func (r *mutationResolver) DeleteMarker(ctx context.Context, id int) (any, error) {
	err := r.MarkerRepository.DeleteMarker(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteMarkerByUUID is the resolver for the DeleteMarkerByUuid field.
func (r *mutationResolver) DeleteMarkerByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.MarkerRepository.DeleteMarkerByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneMarker is the resolver for the GetOneMarker field.
func (r *queryResolver) GetOneMarker(ctx context.Context, id int) (any, error) {
	marker, err := r.MarkerRepository.GetMarkerByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return marker, nil
}

// GetOneMarkerByUUID is the resolver for the GetOneMarkerByUuid field.
func (r *queryResolver) GetOneMarkerByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	marker, err := r.MarkerRepository.GetMarkerByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return marker, nil
}

// GetAllMarkers is the resolver for the GetAllMarkers field.
func (r *queryResolver) GetAllMarkers(ctx context.Context) ([]any, error) {
	markers, err := r.MarkerRepository.GetAllMarkers(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(markers))
	for i, marker := range markers {
		response[i] = marker
	}

	return response, nil
}

// PageMarker is the resolver for the PageMarker field.
func (r *queryResolver) PageMarker(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.MarkerRepository.PageMarker(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
