package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"log"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateMenu is the resolver for the CreateMenu field.
func (r *mutationResolver) CreateMenu(ctx context.Context, createMenuInput models.CreateMenuInput) (any, error) {
	menu := &models.Menu{
		Code:     createMenuInput.Code,
		Name:     createMenuInput.Name,
		URL:      createMenuInput.URL,
		Level:    createMenuInput.Level,
		MenuID:   createMenuInput.MenuID,
		Sequence: createMenuInput.Sequence,
		Show:     createMenuInput.Show,
		Icon:     createMenuInput.Icon,
	}

	response, err := r.MenuRepository.CreateMenu(ctx, menu)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateMenu is the resolver for the UpdateMenu field.
func (r *mutationResolver) UpdateMenu(ctx context.Context, id int, updateMenuInput models.UpdateMenuInput) (any, error) {
	menu := &models.Menu{
		Code:     updateMenuInput.Code,
		Name:     updateMenuInput.Name,
		URL:      updateMenuInput.URL,
		Level:    updateMenuInput.Level,
		MenuID:   updateMenuInput.MenuID,
		Sequence: updateMenuInput.Sequence,
		Show:     updateMenuInput.Show,
		Icon:     updateMenuInput.Icon,
	}

	response, err := r.MenuRepository.UpdateMenu(ctx, int32(id), menu)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateMenuByUUID is the resolver for the UpdateMenuByUuid field.
func (r *mutationResolver) UpdateMenuByUUID(ctx context.Context, uuid uuid.UUID, updateMenuInput models.UpdateMenuInput) (any, error) {
	menu := &models.Menu{
		Code:     updateMenuInput.Code,
		Name:     updateMenuInput.Name,
		URL:      updateMenuInput.URL,
		Level:    updateMenuInput.Level,
		MenuID:   updateMenuInput.MenuID,
		Sequence: updateMenuInput.Sequence,
		Show:     updateMenuInput.Show,
		Icon:     updateMenuInput.Icon,
	}
	log.Print(updateMenuInput)
	response, err := r.MenuRepository.UpdateMenuByUUID(ctx, uuid.String(), menu)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteMenu is the resolver for the DeleteMenu field.
func (r *mutationResolver) DeleteMenu(ctx context.Context, id int) (any, error) {
	err := r.MenuRepository.DeleteMenu(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteMenuByUUID is the resolver for the DeleteMenuByUuid field.
func (r *mutationResolver) DeleteMenuByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.MenuRepository.DeleteMenuByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneMenu is the resolver for the GetOneMenu field.
func (r *queryResolver) GetOneMenu(ctx context.Context, id int) (any, error) {
	menu, err := r.MenuRepository.GetMenuByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return menu, nil
}

// GetOneMenuByUUID is the resolver for the GetOneMenuByUuid field.
func (r *queryResolver) GetOneMenuByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	menu, err := r.MenuRepository.GetMenuByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return menu, nil
}

// GetAllMenus is the resolver for the GetAllMenus field.
func (r *queryResolver) GetAllMenus(ctx context.Context) ([]any, error) {
	menus, err := r.MenuRepository.GetAllMenus(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(menus))
	for i, menu := range menus {
		response[i] = menu
	}

	return response, nil
}

// GetMenuParent is the resolver for the GetMenuParent field.
func (r *queryResolver) GetMenuParent(ctx context.Context, roleID int) ([]any, error) {
	menus, err := r.MenuRepository.GetMenuParent(ctx, roleID)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(menus))
	for i, menu := range menus {
		response[i] = menu
	}

	return response, nil
}

// GetMenuFlat is the resolver for the GetMenuFlat field.
func (r *queryResolver) GetMenuFlat(ctx context.Context, roleID int) ([]any, error) {
	menus, err := r.MenuRepository.GetMenuFlat(ctx, roleID)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(menus))
	for i, menu := range menus {
		response[i] = menu
	}

	return response, nil
}

// GetMenuAllParents is the resolver for the GetMenuAllParents field.
func (r *queryResolver) GetMenuAllParents(ctx context.Context) ([]any, error) {
	menus, err := r.MenuRepository.GetMenuAllParents(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(menus))
	for i, menu := range menus {
		response[i] = menu
	}

	return response, nil
}

// PageMenu is the resolver for the PageMenu field.
func (r *queryResolver) PageMenu(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.MenuRepository.PageMenu(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
