package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"log"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateMenus2role is the resolver for the CreateMenus2role field.
func (r *mutationResolver) CreateMenus2role(ctx context.Context, createMenus2roleInput models.CreateMenus2roleInput) (any, error) {
	menus2role := &models.Menus2role{
		RoleID: createMenus2roleInput.RoleID,
		MenuID: createMenus2roleInput.MenuID,
	}
	response, err := r.Menus2roleRepository.CreateMenus2role(ctx, menus2role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateMenus2role is the resolver for the UpdateMenus2role field.
func (r *mutationResolver) UpdateMenus2role(ctx context.Context, id int, updateMenus2roleInput models.UpdateMenus2roleInput) (any, error) {
	menus2role := &models.Menus2role{
		RoleID: updateMenus2roleInput.RoleID,
		MenuID: updateMenus2roleInput.MenuID,
	}

	response, err := r.Menus2roleRepository.UpdateMenus2role(ctx, int32(id), menus2role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateMenus2roleByUUID is the resolver for the UpdateMenus2roleByUuid field.
func (r *mutationResolver) UpdateMenus2roleByUUID(ctx context.Context, uuid uuid.UUID, updateMenus2roleInput models.UpdateMenus2roleInput) (any, error) {
	menus2role := &models.Menus2role{
		RoleID: updateMenus2roleInput.RoleID,
		MenuID: updateMenus2roleInput.MenuID,
	}
	log.Print(updateMenus2roleInput)
	response, err := r.Menus2roleRepository.UpdateMenus2roleByUUID(ctx, uuid.String(), menus2role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteMenus2role is the resolver for the DeleteMenus2role field.
func (r *mutationResolver) DeleteMenus2role(ctx context.Context, id int) (any, error) {
	err := r.Menus2roleRepository.DeleteMenus2role(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteMenus2roleByUUID is the resolver for the DeleteMenus2roleByUuid field.
func (r *mutationResolver) DeleteMenus2roleByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.Menus2roleRepository.DeleteMenus2roleByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetMenus2roleByMenuUUID is the resolver for the GetMenus2roleByMenuUuid field.
func (r *queryResolver) GetMenus2roleByMenuUUID(ctx context.Context, menuUUID uuid.UUID) ([]any, error) {
	menus2roles, err := r.Menus2roleRepository.GetMenus2roleByMenuUUID(ctx, menuUUID.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(menus2roles))
	for i, menus2role := range menus2roles {
		response[i] = menus2role
	}

	return response, nil
}

// GetOneMenus2role is the resolver for the GetOneMenus2role field.
func (r *queryResolver) GetOneMenus2role(ctx context.Context, id int) (any, error) {
	menus2role, err := r.Menus2roleRepository.GetMenus2roleByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return menus2role, nil
}

// GetOneMenus2roleByUUID is the resolver for the GetOneMenus2roleByUuid field.
func (r *queryResolver) GetOneMenus2roleByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	menus2role, err := r.Menus2roleRepository.GetMenus2roleByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return menus2role, nil
}

// GetAllMenus2roles is the resolver for the GetAllMenus2roles field.
func (r *queryResolver) GetAllMenus2roles(ctx context.Context) ([]any, error) {
	menus2roles, err := r.Menus2roleRepository.GetAllMenus2roles(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(menus2roles))
	for i, menus2role := range menus2roles {
		response[i] = menus2role
	}

	return response, nil
}

// PageMenus2role is the resolver for the PageMenus2role field.
func (r *queryResolver) PageMenus2role(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.Menus2roleRepository.PageMenus2role(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
