package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateProfile is the resolver for the CreateProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, createProfileInput models.CreateProfileInput) (any, error) {
	profile := &models.Profile{
		Name:    createProfileInput.Name,
		UserID:  createProfileInput.UserID,
		Address: createProfileInput.Address,
	}
	response, err := r.ProfileRepository.CreateProfile(ctx, profile)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateProfile is the resolver for the UpdateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, id int, updateProfileInput models.UpdateProfileInput) (any, error) {
	profile := &models.Profile{
		Name:    updateProfileInput.Name,
		UserID:  updateProfileInput.UserID,
		Address: updateProfileInput.Address,
	}

	response, err := r.ProfileRepository.UpdateProfile(ctx, int32(id), profile)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateProfileByUUID is the resolver for the UpdateProfileByUuid field.
func (r *mutationResolver) UpdateProfileByUUID(ctx context.Context, uuid uuid.UUID, updateProfileInput models.UpdateProfileInput) (any, error) {
	profile := &models.Profile{
		Name:    updateProfileInput.Name,
		UserID:  updateProfileInput.UserID,
		Address: updateProfileInput.Address,
	}

	response, err := r.ProfileRepository.UpdateProfileByUUID(ctx, uuid.String(), profile)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteProfile is the resolver for the DeleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context, id int) (any, error) {
	err := r.ProfileRepository.DeleteProfile(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteProfileByUUID is the resolver for the DeleteProfileByUuid field.
func (r *mutationResolver) DeleteProfileByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.ProfileRepository.DeleteProfileByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneProfile is the resolver for the GetOneProfile field.
func (r *queryResolver) GetOneProfile(ctx context.Context, id int) (any, error) {
	profile, err := r.ProfileRepository.GetProfileByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return profile, nil
}

// GetOneProfileByUUID is the resolver for the GetOneProfileByUuid field.
func (r *queryResolver) GetOneProfileByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	profile, err := r.ProfileRepository.GetProfileByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return profile, nil
}

// GetAllProfiles is the resolver for the GetAllProfiles field.
func (r *queryResolver) GetAllProfiles(ctx context.Context) ([]any, error) {
	profiles, err := r.ProfileRepository.GetAllProfiles(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(profiles))
	for i, profile := range profiles {
		response[i] = profile
	}

	return response, nil
}

// PageProfile is the resolver for the PageProfile field.
func (r *queryResolver) PageProfile(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.ProfileRepository.PageProfile(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
