package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateRole is the resolver for the CreateRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, createRoleInput models.CreateRoleInput) (any, error) {
	role := &models.Role{
		Code: createRoleInput.Code,
		Name: createRoleInput.Name,
	}
	response, err := r.RoleRepository.CreateRole(ctx, role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateRole is the resolver for the UpdateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id int, updateRoleInput models.UpdateRoleInput) (any, error) {
	role := &models.Role{
		Code: updateRoleInput.Code,
		Name: updateRoleInput.Name,
	}

	response, err := r.RoleRepository.UpdateRole(ctx, int32(id), role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateRoleByUUID is the resolver for the UpdateRoleByUuid field.
func (r *mutationResolver) UpdateRoleByUUID(ctx context.Context, uuid uuid.UUID, updateRoleInput *models.UpdateRoleInput) (any, error) {
	role := &models.Role{
		Code: updateRoleInput.Code,
		Name: updateRoleInput.Name,
	}

	response, err := r.RoleRepository.UpdateRoleByUUID(ctx, uuid.String(), role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteRole is the resolver for the DeleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id int) (any, error) {
	err := r.RoleRepository.DeleteRole(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteRoleByUUID is the resolver for the DeleteRoleByUuid field.
func (r *mutationResolver) DeleteRoleByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.RoleRepository.DeleteRoleByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneRole is the resolver for the GetOneRole field.
func (r *queryResolver) GetOneRole(ctx context.Context, id int) (any, error) {
	role, err := r.RoleRepository.GetRoleByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return role, nil
}

// GetOneRoleByUUID is the resolver for the GetOneRoleByUuid field.
func (r *queryResolver) GetOneRoleByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	role, err := r.RoleRepository.GetRoleByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return role, nil
}

// GetAllRoles is the resolver for the GetAllRoles field.
func (r *queryResolver) GetAllRoles(ctx context.Context) ([]any, error) {
	roles, err := r.RoleRepository.GetAllRoles(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(roles))
	for i, role := range roles {
		response[i] = role
	}

	return response, nil
}

// PageRole is the resolver for the PageRole field.
func (r *queryResolver) PageRole(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.RoleRepository.PageRole(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
