package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateShip is the resolver for the CreateShip field.
func (r *mutationResolver) CreateShip(ctx context.Context, createShipInput models.CreateShipInput) (any, error) {
	ship := &models.Ship{
		Name:        createShipInput.Name,
		Number:      createShipInput.Number,
		Description: createShipInput.Description,
	}
	response, err := r.ShipRepository.CreateShip(ctx, ship)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateShip is the resolver for the UpdateShip field.
func (r *mutationResolver) UpdateShip(ctx context.Context, id int, updateShipInput models.UpdateShipInput) (any, error) {
	ship := &models.Ship{
		Name:        updateShipInput.Name,
		Number:      updateShipInput.Number,
		Description: updateShipInput.Description,
	}

	response, err := r.ShipRepository.UpdateShip(ctx, int32(id), ship)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateShipByUUID is the resolver for the UpdateShipByUuid field.
func (r *mutationResolver) UpdateShipByUUID(ctx context.Context, uuid uuid.UUID, updateShipInput models.UpdateShipInput) (any, error) {
	ship := &models.Ship{
		Name:        updateShipInput.Name,
		Number:      updateShipInput.Number,
		Description: updateShipInput.Description,
	}

	response, err := r.ShipRepository.UpdateShipByUUID(ctx, uuid.String(), ship)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteShip is the resolver for the DeleteShip field.
func (r *mutationResolver) DeleteShip(ctx context.Context, id int) (any, error) {
	err := r.ShipRepository.DeleteShip(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteShipByUUID is the resolver for the DeleteShipByUuid field.
func (r *mutationResolver) DeleteShipByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.ShipRepository.DeleteShipByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetOneShip is the resolver for the GetOneShip field.
func (r *queryResolver) GetOneShip(ctx context.Context, id int) (any, error) {
	ship, err := r.ShipRepository.GetShipByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return ship, nil
}

// GetOneShipByUUID is the resolver for the GetOneShipByUuid field.
func (r *queryResolver) GetOneShipByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	ship, err := r.ShipRepository.GetShipByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return ship, nil
}

// GetAllShips is the resolver for the GetAllShips field.
func (r *queryResolver) GetAllShips(ctx context.Context) ([]any, error) {
	ships, err := r.ShipRepository.GetAllShips(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(ships))
	for i, ship := range ships {
		response[i] = ship
	}

	return response, nil
}

// GetAllBigShips is the resolver for the GetAllBigShips field.
func (r *queryResolver) GetAllBigShips(ctx context.Context) ([]any, error) {
	ships, err := r.ShipMongodistory.GetAllBigShips(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(ships))
	for i, ship := range ships {
		response[i] = ship
	}

	return response, nil
}

// GetShipsByDatetime is the resolver for the GetShipsByDatetime field.
func (r *queryResolver) GetShipsByDatetime(ctx context.Context, durationTimeInput *models.DurationTimeInput, mmsiList []int64) ([]any, error) {
	// log.Print(mmsiList)
	// mmsiList16 := make([]int16, len(mmsiList))

	// for i, mmsi := range mmsiList {
	// 	mmsiList16[i] = int16(mmsi)
	// }

	ships, err := r.ShipMongotory.GetShipsByDatetime(*durationTimeInput, mmsiList)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(ships))
	for i, ship := range ships {
		response[i] = ship
	}

	return response, nil
}

// GetMobShips is the resolver for the GetMobShips field.
func (r *queryResolver) GetMobShips(ctx context.Context, durationTimeInput *models.DurationTimeInput) ([]any, error) {
	ships, err := r.ShipMongotory.GetMobShips(*durationTimeInput)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(ships))
	for i, ship := range ships {
		response[i] = ship
	}

	return response, nil
}

// PageShip is the resolver for the PageShip field.
func (r *queryResolver) PageShip(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.ShipRepository.PageShip(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
