package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateUsers2role is the resolver for the CreateUsers2role field.
func (r *mutationResolver) CreateUsers2role(ctx context.Context, createUsers2roleInput models.CreateUsers2roleInput) (any, error) {
	users2role := &models.Users2role{
		RoleID: createUsers2roleInput.RoleID,
		UserID: createUsers2roleInput.UserID,
	}
	response, err := r.Users2roleRepository.CreateUsers2role(ctx, users2role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateUsers2role is the resolver for the UpdateUsers2role field.
func (r *mutationResolver) UpdateUsers2role(ctx context.Context, id int, updateUsers2roleInput models.UpdateUsers2roleInput) (any, error) {
	users2role := &models.Users2role{
		RoleID: updateUsers2roleInput.RoleID,
		UserID: updateUsers2roleInput.UserID,
	}

	response, err := r.Users2roleRepository.UpdateUsers2role(ctx, int32(id), users2role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateUsers2roleByUUID is the resolver for the UpdateUsers2roleByUuid field.
func (r *mutationResolver) UpdateUsers2roleByUUID(ctx context.Context, uuid uuid.UUID, updateUsers2roleInput *models.UpdateUsers2roleInput) (any, error) {
	users2role := &models.Users2role{
		RoleID: updateUsers2roleInput.RoleID,
		UserID: updateUsers2roleInput.UserID,
	}

	response, err := r.Users2roleRepository.UpdateUsers2roleByUUID(ctx, uuid.String(), users2role)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// DeleteUsers2role is the resolver for the DeleteUsers2role field.
func (r *mutationResolver) DeleteUsers2role(ctx context.Context, id int) (any, error) {
	err := r.Users2roleRepository.DeleteUsers2role(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteUsers2roleByUUID is the resolver for the DeleteUsers2roleByUuid field.
func (r *mutationResolver) DeleteUsers2roleByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.Users2roleRepository.DeleteUsers2roleByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// GetUsers2roleByUserUUID is the resolver for the GetUsers2roleByUserUuid field.
func (r *queryResolver) GetUsers2roleByUserUUID(ctx context.Context, userUUID uuid.UUID) ([]any, error) {
	users2roles, err := r.Users2roleRepository.GetUsers2roleByUserUUID(ctx, userUUID.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(users2roles))
	for i, users2role := range users2roles {
		response[i] = users2role
	}

	return response, nil
}

// GetOneUsers2role is the resolver for the GetOneUsers2role field.
func (r *queryResolver) GetOneUsers2role(ctx context.Context, id int) (any, error) {
	users2role, err := r.Users2roleRepository.GetUsers2roleByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return users2role, nil
}

// GetOneUsers2roleByUUID is the resolver for the GetOneUsers2roleByUuid field.
func (r *queryResolver) GetOneUsers2roleByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	users2role, err := r.Users2roleRepository.GetUsers2roleByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return users2role, nil
}

// GetUsers2roleByRoleID is the resolver for the GetUsers2roleByRoleId field.
func (r *queryResolver) GetUsers2roleByRoleID(ctx context.Context, roleID int) ([]any, error) {
	users2roles, err := r.Users2roleRepository.GetUsers2roleByRoleId(ctx, int32(roleID))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(users2roles))
	for i, users2role := range users2roles {
		response[i] = users2role
	}

	return response, nil
}

// GetAllUsers2roles is the resolver for the GetAllUsers2roles field.
func (r *queryResolver) GetAllUsers2roles(ctx context.Context) ([]any, error) {
	users2roles, err := r.Users2roleRepository.GetAllUsers2roles(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(users2roles))
	for i, users2role := range users2roles {
		response[i] = users2role
	}

	return response, nil
}

// PageUsers2role is the resolver for the PageUsers2role field.
func (r *queryResolver) PageUsers2role(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.Users2roleRepository.PageUsers2role(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
