package interfaces

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/error_handlers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/helpers"
	"github.com/khoirulhasin/untirta_api/app/infrastructures/pkg"
	"github.com/khoirulhasin/untirta_api/app/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, loginInput *models.LoginInput) (any, error) {
	response, err := r.UserRepository.Login(ctx, loginInput.Account, loginInput.Password)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, createUserInput models.CreateUserInput) (any, error) {
	password, _ := helpers.HashPassword(createUserInput.Password)
	user := &models.User{
		Username: createUserInput.Username,
		Email:    createUserInput.Email,
		Password: password,
		RoleID:   &createUserInput.RoleID,
	}
	response, err := r.UserRepository.CreateUser(ctx, user)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// CreateUserOwner is the resolver for the CreateUserOwner field.
func (r *mutationResolver) CreateUserOwner(ctx context.Context, createUserOwnerInput models.CreateUserOwnerInput) (any, error) {
	password, _ := helpers.HashPassword(createUserOwnerInput.Password)
	user := &models.User{
		Username: createUserOwnerInput.Username,
		Email:    createUserOwnerInput.Email,
		Password: password,
	}

	roleId := 3

	user.RoleID = &roleId
	userResponse, err := r.UserRepository.CreateUser(ctx, user)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	_, err = r.CreateUsers2role(ctx, models.CreateUsers2roleInput{
		UserID: userResponse.ID,
		RoleID: roleId,
	})

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response, err := r.ProfileRepository.CreateProfile(ctx, &models.Profile{
		UserID:  userResponse.ID,
		Name:    createUserOwnerInput.Name,
		Address: createUserOwnerInput.Address,
	})

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateUser is the resolver for the UpdateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int, updateUserInput models.UpdateUserInput) (any, error) {
	user := &models.User{
		Username: updateUserInput.Username,
		Email:    updateUserInput.Email,
	}

	response, err := r.UserRepository.UpdateUser(ctx, int32(id), user)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateUserByUUID is the resolver for the UpdateUserByUuid field.
func (r *mutationResolver) UpdateUserByUUID(ctx context.Context, uuid uuid.UUID, updateUserInput models.UpdateUserInput) (any, error) {
	user := &models.User{
		Username: updateUserInput.Username,
		Email:    updateUserInput.Email,
	}

	response, err := r.UserRepository.UpdateUserByUUID(ctx, uuid.String(), user)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdateUserOwner is the resolver for the UpdateUserOwner field.
func (r *mutationResolver) UpdateUserOwner(ctx context.Context, id int, updateUserOwnerInput models.UpdateUserOwnerInput) (any, error) {
	user := &models.User{
		Username: updateUserOwnerInput.Username,
		Email:    updateUserOwnerInput.Email,
	}

	roleId := 3

	user.RoleID = &roleId
	response, err := r.UserRepository.UpdateUser(ctx, int32(id), user)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	profile, err := r.ProfileRepository.GetProfileByUserID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	if profile == nil {
		_, err := r.ProfileRepository.CreateProfile(ctx, &models.Profile{
			Name:    updateUserOwnerInput.Name,
			Address: updateUserOwnerInput.Address,
			UserID:  id,
		})
		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	} else {
		_, err := r.ProfileRepository.UpdateProfileByUserID(ctx, int32(id), &models.Profile{
			Name:    updateUserOwnerInput.Name,
			Address: updateUserOwnerInput.Address,
		})

		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	}

	return response, nil
}

// UpdateUserOwnerByUUID is the resolver for the UpdateUserOwnerByUuid field.
func (r *mutationResolver) UpdateUserOwnerByUUID(ctx context.Context, uuid uuid.UUID, updateUserOwnerInput models.UpdateUserOwnerInput) (any, error) {
	user := &models.User{
		Username: updateUserOwnerInput.Username,
		Email:    updateUserOwnerInput.Email,
	}

	roleId := 3

	user.RoleID = &roleId
	response, err := r.UserRepository.UpdateUserByUUID(ctx, uuid.String(), user)
	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	user, err = r.UserRepository.GetUserByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}
	profile, err := r.ProfileRepository.GetProfileByUserID(ctx, int32(user.ID))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	if profile == nil {
		_, err := r.ProfileRepository.CreateProfile(ctx, &models.Profile{
			Name:    updateUserOwnerInput.Name,
			Address: updateUserOwnerInput.Address,
			UserID:  user.ID,
		})
		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	} else {
		_, err := r.ProfileRepository.UpdateProfileByUserID(ctx, int32(user.ID), &models.Profile{
			Name:    updateUserOwnerInput.Name,
			Address: updateUserOwnerInput.Address,
		})

		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	}

	return response, nil
}

// UpdateUserProfile is the resolver for the UpdateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, id int, updateUserProfileInput models.UpdateUserProfileInput) (any, error) {
	user := &models.User{
		Username: updateUserProfileInput.Username,
		Email:    updateUserProfileInput.Email,
	}

	token, err := helpers.GetToken(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	userId, err := helpers.GetUserID(token.(string))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	roleId, err := r.UserRepository.GetUserByID(ctx, int32(userId))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	user.RoleID = roleId.RoleID
	response, err := r.UserRepository.UpdateUser(ctx, int32(id), user)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	profile, err := r.ProfileRepository.GetProfileByUserID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	if profile == nil {
		_, err := r.ProfileRepository.CreateProfile(ctx, &models.Profile{
			Name:    updateUserProfileInput.Name,
			Address: updateUserProfileInput.Address,
			UserID:  id,
		})
		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	} else {
		_, err := r.ProfileRepository.UpdateProfileByUserID(ctx, int32(id), &models.Profile{
			Name:    updateUserProfileInput.Name,
			Address: updateUserProfileInput.Address,
		})

		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	}

	return response, nil
}

// UpdateUserOwnerByUUID is the resolver for the UpdateUserOwnerByUuid field.
func (r *mutationResolver) UpdateUserProfileByUUID(ctx context.Context, uuid uuid.UUID, updateUserProfileInput models.UpdateUserProfileInput) (any, error) {
	user := &models.User{
		Username: updateUserProfileInput.Username,
		Email:    updateUserProfileInput.Email,
	}

	token, err := helpers.GetToken(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	userId, err := helpers.GetUserID(token.(string))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	roleId, err := r.UserRepository.GetUserByID(ctx, int32(userId))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	user.RoleID = roleId.RoleID

	response, err := r.UserRepository.UpdateUserByUUID(ctx, uuid.String(), user)
	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	user, err = r.UserRepository.GetUserByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}
	profile, err := r.ProfileRepository.GetProfileByUserID(ctx, int32(user.ID))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	if profile == nil {
		_, err := r.ProfileRepository.CreateProfile(ctx, &models.Profile{
			Name:    updateUserProfileInput.Name,
			Address: updateUserProfileInput.Address,
			UserID:  user.ID,
		})
		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	} else {
		_, err := r.ProfileRepository.UpdateProfileByUserID(ctx, int32(user.ID), &models.Profile{
			Name:    updateUserProfileInput.Name,
			Address: updateUserProfileInput.Address,
		})

		if err != nil {
			return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
		}
	}

	return response, nil
}

// DeleteUser is the resolver for the DeleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int) (any, error) {
	err := r.UserRepository.DeleteUser(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// DeleteUserByUUID is the resolver for the DeleteUserByUuid field.
func (r *mutationResolver) DeleteUserByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	err := r.UserRepository.DeleteUserByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return nil, nil
}

// ChangePassword is the resolver for the ChangePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, changePasswordInput models.ChangePasswordInput) (any, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - ChangePassword"))
}

// UpdatePassword is the resolver for the UpdatePassword field.
func (r *mutationResolver) UpdatePassword(ctx context.Context, id int, passwordInput models.PasswordInput) (any, error) {
	password, _ := helpers.HashPassword(passwordInput.Password)
	response, err := r.UserRepository.UpdatePassword(ctx, int32(id), password)
	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// UpdatePasswordByUUID is the resolver for the UpdatePasswordByUuid field.
func (r *mutationResolver) UpdatePasswordByUUID(ctx context.Context, uuid uuid.UUID, passwordInput models.PasswordInput) (any, error) {
	password, _ := helpers.HashPassword(passwordInput.Password)
	response, err := r.UserRepository.UpdatePasswordByUUID(ctx, uuid.String(), password)
	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return response, nil
}

// GetUser is the resolver for the GetUser field.
func (r *queryResolver) GetUser(ctx context.Context) (any, error) {
	token, _ := helpers.GetToken(ctx)

	userId, _ := helpers.GetUserID(token.(string))
	user, err := r.UserRepository.GetUserByID(ctx, int32(userId))
	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return user, nil
}

// GetOneUser is the resolver for the GetOneUser field.
func (r *queryResolver) GetOneUser(ctx context.Context, id int) (any, error) {
	user, err := r.UserRepository.GetUserByID(ctx, int32(id))

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return user, nil
}

// GetOneUserByUUID is the resolver for the GetOneUserByUuid field.
func (r *queryResolver) GetOneUserByUUID(ctx context.Context, uuid uuid.UUID) (any, error) {
	user, err := r.UserRepository.GetUserByUUID(ctx, uuid.String())

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return user, nil
}

// GetAllUsers is the resolver for the GetAllUsers field.
func (r *queryResolver) GetAllUsers(ctx context.Context) ([]any, error) {
	users, err := r.UserRepository.GetAllUsers(ctx)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	response := make([]any, len(users))
	for i, user := range users {
		response[i] = user
	}

	return response, nil
}

// PageUser is the resolver for the PageUser field.
func (r *queryResolver) PageUser(ctx context.Context, pageInput *models.PageInput) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	response, err := r.UserRepository.PageUser(ctx, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}

// PageUserByRoleIds is the resolver for the PageUserByRoleIds field.
func (r *queryResolver) PageUserByRoleIds(ctx context.Context, pageInput *models.PageInput, roleIds []*int) (*models.Pagination, error) {
	limit, offset, sortField, sortOrder, search, _ := pkg.PageInputIsNil(pageInput)

	pagination := models.Pagination{
		Limit:     &limit,
		Offset:    &offset,
		SortField: &sortField,
		SortOrder: &sortOrder,
		Search:    &search,
	}

	// Convert roleIDs from []*int to []int32 with nil check
	var convertedRoleIDs []int32
	if roleIds != nil {
		convertedRoleIDs = make([]int32, 0, len(roleIds))
		for _, id := range roleIds {
			if id != nil {
				convertedRoleIDs = append(convertedRoleIDs, int32(*id))
			}
		}
	}
	response, err := r.UserRepository.PageUserByRoleIDs(ctx, convertedRoleIDs, pagination)

	if err != nil {
		return nil, gqlerror.Errorf(error_handlers.ParsePGError(err))
	}

	return &response, nil
}
