// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Data interface {
	IsData()
}

type Answer struct {
	ID         string    `json:"id"`
	QuestionID string    `json:"questionId"`
	OptionID   string    `json:"optionId"`
	IsCorrect  bool      `json:"isCorrect"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

func (Answer) IsData() {}

type ListResponse struct {
	Message string `json:"message"`
	Status  int32  `json:"status"`
	Data    []Data `json:"data,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Question struct {
	ID             string            `json:"id"`
	Title          string            `json:"title"`
	QuestionOption []*QuestionOption `json:"questionOption,omitempty"`
	CreatedAt      time.Time         `json:"createdAt"`
	UpdatedAt      time.Time         `json:"updatedAt"`
}

func (Question) IsData() {}

type QuestionInput struct {
	Title   string                 `json:"title"`
	Options []*QuestionOptionInput `json:"options"`
}

type QuestionOption struct {
	ID         string    `json:"id"`
	QuestionID string    `json:"questionId"`
	Title      string    `json:"title"`
	Position   int32     `json:"position"`
	IsCorrect  bool      `json:"isCorrect"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

func (QuestionOption) IsData() {}

type QuestionOptionInput struct {
	Title     string `json:"title"`
	Position  int32  `json:"position"`
	IsCorrect bool   `json:"isCorrect"`
}

type Response struct {
	Message string `json:"message"`
	Status  int32  `json:"status"`
	Data    Data   `json:"data,omitempty"`
}
